[package]
name = "orb"
version = "0.1.0"
edition = "2024"

[dependencies]
# math 
scilib = "1.0.0"
num = "0.4.3"

## wgpu rendering stuff
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
log = "0.4"
wgpu = "26.0"
pollster = "0.4"

